"""Hybrid / GraphRAG page."""
import streamlit as st
from ui.api_client import api_post

st.set_page_config(page_title="Hybrid / GraphRAG — AegisOps", page_icon="🧠", layout="wide")
st.title("🧠 Hybrid Retrieval & GraphRAG")
st.caption(
    "Evidence-grounded answers combining semantic search, graph traversal, "
    "and LLM synthesis over canonical PostgreSQL memories."
)

tab_rag, tab_hybrid = st.tabs(["GraphRAG Query", "Hybrid Retrieval"])

with tab_rag:
    question = st.text_area(
        "Operational question",
        placeholder="What failures have been observed on pump P-102 at the west facility?",
        height=100,
    )
    col1, col2 = st.columns(2)
    anchor_id = col1.text_input("Anchor Memory ID (optional)", "")
    ctx_limit = col2.slider("Evidence context limit", 1, 10, 5)

    if st.button("Ask AegisOps", type="primary") and question:
        with st.spinner("Retrieving evidence and generating answer..."):
            result = api_post(
                "/api/v1/graphrag/query",
                {
                    "question": question,
                    "anchor_memory_id": anchor_id or None,
                    "context_limit": ctx_limit,
                },
            )

        if result and "error" not in result:
            st.divider()
            st.subheader("Answer")

            if result.get("is_synthetic_response"):
                st.warning(
                    "⚠️ This answer was generated by the deterministic test provider. "
                    "Set `OPENAI_API_KEY` in your `.env` for real LLM responses."
                )

            st.markdown(result.get("answer", ""))

            st.divider()
            col1, col2, col3 = st.columns(3)
            col1.metric("Evidence Items", result.get("evidence_count", 0))
            col2.metric("Model", result.get("model_name", ""))
            col3.metric("Total Latency", f"{result.get('total_latency_ms', 0):.0f}ms")

            st.divider()
            st.subheader("Evidence Used")
            evidence = result.get("evidence", [])
            for i, e in enumerate(evidence, 1):
                with st.expander(
                    f"[Memory {i}] {e.get('title', '')} — {e.get('memory_type', '')} "
                    f"(source: {e.get('retrieval_source', '')})"
                ):
                    c1, c2 = st.columns(2)
                    c1.metric("Confidence", f"{e.get('confidence', 0):.0%}")
                    c2.metric("Asset", e.get("asset_id") or "—")
                    st.markdown(e.get("content_preview", ""))
                    st.caption(f"Memory ID: `{e.get('memory_id', '')}`")
        else:
            st.error("GraphRAG query failed.")
            if result:
                st.json(result)

with tab_hybrid:
    hybrid_query = st.text_input("Search query", placeholder="bearing wear fault")
    mode = st.radio("Retrieval mode", ["hybrid", "semantic", "graph"], horizontal=True)
    hlimit = st.slider("Max results", 1, 20, 10)
    hops = st.slider("Graph hops (hybrid/graph mode)", 1, 5, 2)

    if st.button("Retrieve", type="primary") and hybrid_query:
        with st.spinner("Retrieving..."):
            result = api_post(
                "/api/v1/search/hybrid",
                {
                    "query": hybrid_query,
                    "mode": mode,
                    "limit": hlimit,
                    "graph_hops": hops,
                },
            )

        if result and "error" not in result:
            results = result.get("results", [])
            st.success(f"{len(results)} results via {mode} retrieval")

            for r in results:
                src = r.get("retrieval_source", "")
                icon = "🔵" if src == "semantic" else "🟣" if src == "graph" else "🟢"
                with st.expander(
                    f"{icon} {r.get('title', '—')} [{r.get('memory_type', '')}]"
                ):
                    c1, c2, c3 = st.columns(3)
                    c1.write(f"**Source:** {src}")
                    c2.write(f"**Score:** {r.get('semantic_score', 'N/A')}")
                    c3.write(f"**Asset:** {r.get('asset_id') or '—'}")
                    st.caption(r.get("content_preview", ""))
        else:
            st.error("Retrieval failed.")
