"""
Deterministic test LLM provider.

Returns a deterministic template-based response built from the evidence
context. Used when no API key is available. Outputs are clearly marked as
synthetic and are NOT suitable for production use.
"""
from __future__ import annotations

from app.graphrag.provider import LLMMessage, LLMProvider, LLMResponse

_MODEL_NAME = "deterministic-test-v1"


class DeterministicTestProvider(LLMProvider):
    """
    Template-based response generator for testing.

    Responses are built from context keywords — NOT semantically meaningful.
    Always mark generated content as synthetic in production.
    """

    def generate(
        self,
        messages: list[LLMMessage],
        temperature: float = 0.0,
        max_tokens: int = 1024,
    ) -> LLMResponse:
        # Extract user question and evidence summary from messages
        user_msg = next(
            (m.content for m in messages if m.role == "user"), ""
        )
        system_msg = next(
            (m.content for m in messages if m.role == "system"), ""
        )

        # Count evidence items mentioned in context
        evidence_count = system_msg.count("[Memory") + system_msg.count("Memory ID")

        content = (
            f"[SYNTHETIC RESPONSE — deterministic-test-v1]\n\n"
            f"Based on {evidence_count} retrieved memory records, the following "
            f"analysis addresses: {user_msg[:200]}\n\n"
            f"The evidence context contains operational observations from PostgreSQL. "
            f"Key findings are derived deterministically from the provided context. "
            f"Confidence is proportional to the number and recency of supporting records.\n\n"
            f"Note: This response was generated by the deterministic test provider. "
            f"Configure OPENAI_API_KEY and set LLM_PROVIDER=openai for real responses."
        )

        return LLMResponse(
            content=content,
            model_name=_MODEL_NAME,
            prompt_tokens=len(system_msg.split()) + len(user_msg.split()),
            completion_tokens=len(content.split()),
        )

    def get_model_name(self) -> str:
        return _MODEL_NAME


class OpenAIProvider(LLMProvider):
    """
    OpenAI API provider.

    Requires: pip install openai and OPENAI_API_KEY environment variable.
    Model defaults to gpt-4o-mini to minimize cost.
    """

    def __init__(self, api_key: str, model: str = "gpt-4o-mini") -> None:
        try:
            from openai import OpenAI
            self._client = OpenAI(api_key=api_key)
        except ImportError:
            raise RuntimeError(
                "openai package required. Install with: pip install openai"
            )
        self._model = model

    def generate(
        self,
        messages: list[LLMMessage],
        temperature: float = 0.0,
        max_tokens: int = 1024,
    ) -> LLMResponse:
        from openai import OpenAI

        oai_messages = [{"role": m.role, "content": m.content} for m in messages]
        response = self._client.chat.completions.create(
            model=self._model,
            messages=oai_messages,
            temperature=temperature,
            max_tokens=max_tokens,
        )
        choice = response.choices[0]
        return LLMResponse(
            content=choice.message.content or "",
            model_name=self._model,
            prompt_tokens=response.usage.prompt_tokens,
            completion_tokens=response.usage.completion_tokens,
        )

    def get_model_name(self) -> str:
        return self._model
